[package]
name = "nerdfix"
version = "0.0.0"
authors = ["loichyan <loichyan@foxmail.com>"]
license = "MIT OR Apache-2.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
codespan-reporting = "0.11"
colored = "2.0"
extend = "1.1"
indicium = "0.4"
inquire = "0.6"
ngrammatic = "0.4"
once_cell = "1.17"
select = "0.6"
thisctx = "0.3"
thiserror = "1.0"

[dependencies.clap]
version = "4.1"
features = ["derive"]
